This is makeindex, version 2.15 [MiKTeX 21.3].
Scanning style file ./krilangs_thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file krilangs_thesis.acn....done (542 entries accepted, 0 rejected).
Sorting entries.......done (5627 comparisons).
Generating output file krilangs_thesis.acr....done (238 lines written, 0 warnings).
Output written in krilangs_thesis.acr.
Transcript written in krilangs_thesis.alg.
